name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android-abi: [armeabi-v7a, arm64-v8a, x86, x86_64]  # List of architectures to build for

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up NDK
      uses: android-actions/setup-ndk@v1.5.0
      with:
        ndk-version: r27b  # Specify the NDK version you want to use

    - name: Build with CMake
      run: |
        mkdir build-android
        cd build-android
        cmake -DCMAKE_TOOLCHAIN_FILE=$NDK_HOME/build-android/cmake/android.toolchain.cmake \
              -DANDROID_ABI=${{ matrix.android-abi }} \
              -DANDROID_PLATFORM=android-21 ..
        make

    # Optionally, you can add steps to upload the built library as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openAPV-android-${{ matrix.android-abi }}
        path: build-android/*
